CREATE TABLE venues (
  venue_id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  image_url TEXT NOT NULL,
  latitude FLOAT NOT NULL,
  longitude FLOAT NOT NULL
);
CREATE TABLE destinations (
  destination_id SERIAL PRIMARY KEY,
  venue_id INTEGER NOT NULL REFERENCES venues ON DELETE CASCADE ON UPDATE CASCADE,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  image_url TEXT NOT NULL,
  latitude FLOAT NOT NULL,
  longitude FLOAT NOT NULL
);
CREATE TABLE waypoints (
  waypoint_id SERIAL PRIMARY KEY,
  venue_id INTEGER NOT NULL REFERENCES venues ON DELETE CASCADE ON UPDATE CASCADE,
  destination_id INTEGER REFERENCES destinations ON DELETE CASCADE ON UPDATE CASCADE,
  latitude FLOAT NOT NULL,
  longitude FLOAT NOT NULL
);
CREATE TABLE paths (
  inNode INTEGER NOT NULL REFERENCES waypoints ON DELETE CASCADE ON UPDATE CASCADE,
  outNode INTEGER NOT NULL REFERENCES waypoints ON DELETE CASCADE ON UPDATE CASCADE,
  venue_id INTEGER NOT NULL REFERENCES venues ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (inNode, outNode)
);